spring:
  application:
    name: benefits-authorizer
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  swagger-ui:
    doc-expansion: none

app:
  initial-balance: 500
